// <auto-generated />
using DesafioProjetoHospedagem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioProjetoHospedagem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250703002427_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioProjetoHospedagem.Models.PessoaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservaModelId")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReservaModelId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("DesafioProjetoHospedagem.Models.ReservaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasReservados")
                        .HasColumnType("int");

                    b.Property<int?>("SuiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuiteId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("DesafioProjetoHospedagem.Models.SuiteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoSuite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorDiaria")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Suites");
                });

            modelBuilder.Entity("DesafioProjetoHospedagem.Models.PessoaModel", b =>
                {
                    b.HasOne("DesafioProjetoHospedagem.Models.ReservaModel", null)
                        .WithMany("Hospedes")
                        .HasForeignKey("ReservaModelId");
                });

            modelBuilder.Entity("DesafioProjetoHospedagem.Models.ReservaModel", b =>
                {
                    b.HasOne("DesafioProjetoHospedagem.Models.SuiteModel", "Suite")
                        .WithMany()
                        .HasForeignKey("SuiteId");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("DesafioProjetoHospedagem.Models.ReservaModel", b =>
                {
                    b.Navigation("Hospedes");
                });
#pragma warning restore 612, 618
        }
    }
}
